//--------------------------------------------------------------------
// Created by Microsemi SmartDesign Tue May 17 09:01:51 2022
// Parameters for CoreDDRMemCtrlr
//--------------------------------------------------------------------


parameter ADDR_MAP_SIG_BITS = 10;
parameter ADDR_WIDTH = 34;
parameter ADDR_WIDTH_TS = 37;
parameter ALLOW_PARTIAL_BURSTS = 0;
parameter AXI0_ENABLE_PAR = 
parameter AXI1_ENABLE_PAR = 
parameter AXI2_ENABLE_PAR = 
parameter AXI3_ENABLE_PAR = 
parameter AXI4_ENABLE_PAR = 
parameter AXI5_ENABLE_PAR = 
parameter AXI6_ENABLE_PAR = 
parameter AXI7_ENABLE_PAR = 
parameter AXI_ADDR_WIDTH = 32;
parameter AXI_AWUSERTAG_EN = 
parameter AXI_AWUSERTAG_WIDTH = 4;
parameter AXI_DATA_WIDTH = 64;
parameter AXI_ECC_SUPPORT = 
parameter AXI_ENABLE_INTRAPORT_REORDER = 
parameter AXI_LEN_WIDTH = 8;
parameter AXI_SINGLE_CLOCK_MODE = 0;
parameter AXI_SLAVE_ID_WIDTH = 6;
parameter AXI_SLAVE_TYPE = 1;
parameter BANK_GROUP_ADDR_WIDTH = 2;
parameter BURST_SIZE_WIDTH = 13;
parameter BYTE_ADDR_WIDTH = 37;
parameter BYTE_SUBADDRESS_BITS = 4;
parameter BYTES_PER_WORD = 16;
parameter CAC_PIPE_STAGES = 3;
parameter CORE_ADV_D_REQ = 3;
parameter CORE_ADV_R_VALID = 3;
parameter CORE_ADV_RD_START = 3;
parameter CORE_ADV_WR_START = 1;
parameter COREDDRMEMCTRLR_INST_NO = 0;
parameter CTRLR_RANKS = 1;
parameter DESELECT_WHEN_IDLE = 
parameter DFI_ADDRESS_WIDTH = 20;
parameter DFI_ADDRESS_WIDTH_C = 20;
parameter DFI_BANK_WIDTH = 4;
parameter DFI_BANKGROUP_WIDTH = 2;
parameter DFI_CHIP_SELECT_WIDTH = 1;
parameter DFI_CID_WIDTH = 3;
parameter DFI_CONTROL_WIDTH = 1;
parameter DFI_DATA_ENABLE_WIDTH = 2;
parameter DFI_DATA_PHASE_WIDTH = 32;
parameter DFI_DATA_WIDTH = 128;
parameter DFI_DM_PHASE_WIDTH = 4;
parameter DFI_T_PHY_WRDATA = 1;
parameter DFI_WRLVL_SLICE_WIDTH = 2;
parameter DISABLE_BURST_TERMINATE = 
parameter DSIZE = 128;
parameter ECC_ACTIVE_DWIDTH = 16;
parameter ECC_RDDATA_PIPELINE = 
parameter EF_AXI_PAR = 
parameter EF_ECC_PAR = 
parameter EF_LB_PAR = 
parameter EF_MPFE_PAR = 
parameter EF_RMW_PAR = 
parameter ENABLE_3DS = 
parameter ENABLE_REG_D_REQ_OUTPUT = 
parameter FAMILY = 26;
parameter FAST_ACTIVATE = 0;
parameter FASTSDRAM_PIPE_LEVEL = 
parameter FREQ_RATIO = 4;
parameter HDL_license = "O";
parameter LB0_DISABLE_PAR = 
parameter LB1_DISABLE_PAR = 
parameter LB2_DISABLE_PAR = 
parameter LB3_DISABLE_PAR = 
parameter LB4_DISABLE_PAR = 
parameter LB5_DISABLE_PAR = 
parameter LB6_DISABLE_PAR = 
parameter LB7_DISABLE_PAR = 
parameter LOOKAHEAD_AUTOPRECHARGE = 
parameter LOOKAHEAD_PRECHARGE = 
parameter MASK_R_VALID_START_EN = 0;
parameter MAX_SN_WIDTH = 2;
parameter MPFE_PIPELINE_VERSION = 1;
parameter MULTIBURST_LATENCY_MASK = 1;
parameter NIBBLE_DEVICES = 0;
parameter NUM_ALERT_OR_QERR = 1;
parameter NUM_CAC_BUSES = 1;
parameter NUM_CLK_OUTS = 1;
parameter NUM_ECC = 8;
parameter NUMBER_OF_RANKS = 8;
parameter OVERRIDE_EARLY_D_REQ = 0;
parameter OVERRIDE_EARLY_R_VALID = 0;
parameter PD_SR_SUPPORTED = 
parameter PIPELINE_CFG_REGS = 
parameter QM_COMMAND_PIPE_STAGES = 2;
parameter QUEUE_DEPTH = 3;
parameter SDRAM_BANKSTATMODULES = 4;
parameter SYNDROME_REG_PIPELINE = 
parameter TAG_WIDTH = 52;
parameter USE_PHY_RDDATA_VALID = 0;
parameter USE_READ_CAPTURE_MODULE = 
